version: '3.7'

services:

  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adm_videos
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - ../.docker/mysql:/var/lib/mysql:rw
    networks:
      - adm_videos_services

  rabbit:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - adm_videos_services

  keycloak:
    container_name: adm_videos_keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json
      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/key.pem
    ports:
      - "8443:8443"
    command:
      - start-dev --import-realm --optimized --hostname-strict=false
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ../.docker/keycloak/certs:/opt/keycloak/certs:ro
      - ../.docker/keycloak_data:/opt/keycloak/data:rw
    networks:
      - adm_videos_services

networks:
  adm_videos_services:
    external: true